### PR TITLE
Add a title bar/window controls to popovers

### PR DESCRIPTION
**Pull request by nothingislost**
Initial draft for window controls. The min/max/close buttons are not currently hooked up.

More commits needed but just making this public so we can iterate on it and provide feedback.

image

### CODE REVIEW

**Comment by nothingislost** [comment]
Haven't committed this yet but this is what I'm experimenting with currently:

https://user-images.githubusercontent.com/89109712/159372213-17a45961-320b-4daa-8386-0f3cd7cf2a70.mp4

**Comment by nothingislost** [comment]
I've pushed my latest commits which need a bunch of clean up/refactoring but this is what I've come up with so far:

https://user-images.githubusercontent.com/89109712/159412635-6cc55c06-e96f-4cb2-aa00-337789332810.mp4

**Comment by pjeby** [comment]
Will there be a way (e.g. a setting) to show the leaf controls by default, so there isn't always an extra click to access them?  Or perhaps to show the window controls only on hover?

**Comment by nothingislost** [comment]
> Will there be a way (e.g. a setting) to show the leaf controls by default, so there isn't always an extra click to access them? Or perhaps to show the window controls only on hover?

Yep, there will be a setting to show the nav bar by default. Not showing it will be the default state and the plugin setting will allow you to switch that. This way the user interface stays fairly minimal unless people want to opt in to the additional chrome.

**Comment by nothingislost** [comment]
@pjeby I just pushed some additional commits that add the setting to show the navbar by default. When you get a chance, could you try this out and see if you have any additional suggestions? I need to refactor the code a bit but functionally, I think this is pretty close to release.

**Comment by pjeby** [comment]
It works really nicely!  I ended up styling all the titlebar elements as:

```css
{
    background-color: var(--interactive-accent);
    color: var(--text-on-accent);
}
```

...but it was rather difficult due to the complexity of the existing styles; perhaps it would be good if the plugin defined its own variables for the colors, so that themers need only redefine the variables to re-color the title bar, vs needing to do a bunch of overrides for some rather fiddly sub-rules.

(The reason for my style choice, in case you're interested, is that it clearly distinguishes the hover-editor controls from the pane header controls, since they have different functions and behavior.  An unexpected side benefit is that it's much easier to see where my popups are when they're on a white or grey background, especially when minimized.  I also tried using `--background-modifier-cover` for the background, which works nicely to echo the Obsidian titlebar for themes that allow it to exist, but the interactive accent version seemed to be compatible with more themes.)

Anyway, super-thrilled with how it seems to work, one minor glitch though is that if you drag the header icon from a new, unpinned popover, the popover may close before you can finish dragging, thus aborting the action.  Not a show-stopper by any means, and I can always make a PR for it later once I figure out how.  :wink:

**Comment by nothingislost** [comment]
Thanks for the feedback! 

For the unpinned popover drag issue, patching `Workspace.onDragLeaf` to auto pin the popover on drag is the best approach I can think of:

```js
      onDragLeaf(old) {
        return function(event: MouseEvent, leaf: WorkspaceLeaf) {
          let hoverPopover = HoverEditor.forLeaf(leaf);
          hoverPopover?.togglePin(true);
          return old.call(this, event, leaf);
        }
      }
```

**Comment by pjeby** [comment]
Guess I won't need to figure out how after all.  ;-)

As for the CSS, I had to do this:

```css
div.popover.hover-popover .popover-content div.popover-titlebar {
    background-color: var(--interactive-accent);
}

div.popover.hover-popover .popover-content div.popover-titlebar .popover-action,
div.popover.hover-popover .popover-content div.popover-titlebar .popover-title,
div.popover.hover-popover .popover-content div.popover-titlebar .mod-pin-popover {
    color: var(--text-on-accent);
}
```

I mean, I could've used `!important` for some of that, but I try not to use it if I can avoid it.  Basically I'm trying to override what amounts to 6 different text and background color rules here, even without trying to handle the .is-active distinction.

**Comment by pjeby** [comment]
Btw, there is a slight issue where the rename handler is always setting the titlebar text even if that's not the active file in that popover (i.e., if you have two different files open side-by-side in the popover).  Probably there should be a check that the name that was in the title bar matches the "before" basename?  Not really sure the best way to handle that.

**Comment by Obadiahcruz** [comment]
whoa! This looks super cool! the core editor should have this! wow

**Comment by nothingislost** [comment]
@pjeby new CSS variables pushed. I borrowed your --interactive-accent and --text-on-accent idea but I had a hell of a time trying to figure out a good way to provide a way to differentiate --text-on-accent for active elements. I couldn't find an existing variable that worked so I created my own and provided a sane default.

Next step is to turn some of these into style settings.

**Comment by pjeby** [comment]
Looking good!  I notice that the pure white text seems overly bold; I tried dropping the titlebar's font weight to 400 and that seemed to fix it.  For my own use I've settled on making the inactive titlebar background be the Obsidian titlebar background, and the active titlebar background be the interactive accent (with both using text-on-accent in foreground), as it really makes the active window "pop" vs the inactive ones, (Which seems important when you're hiding the pane header(s)!)

While my earlier experiment with `--background-modifier-cover` had some theme compatibility issues, it turns out those were due to my crude CSS hacking, not anything wrong with the variable itself.  I was inadvertently stacking it, and in most themes it's semi-transparent, so layering it made it look weird.  Your precisely targeted use avoids that problem, so if you use it as the inactive background and the interactive-accent as the active background, you can make the default active *foreground* be text-on-accent rather than hardcoded white, neatly solving the defaults issue.

(All that being said, the current defaults are plenty good enough and thoroughly themeable, so thank you!)

Speaking of making the active window pop, I'm noticing now that clicking on the titlebar doesn't activate the contained pane any more, meaning you now have to click in the body to activate it.  I'm not sure how important that is, as I've not yet started using the new version "for real" in the sense that I've only been playing with it to test the branch a little yesterday and today.  It might not be a big deal at all.

**Comment by pjeby** [comment]
`updateLeaves()` was also closing the popover once there were no leaves in it, so the recent commit broke the ability to close a popover from the keyboard by closing the leaf or leaves in it.

**Comment by nothingislost** [comment]
Sadly since `--background-modifier-cover` is transparent, it doesn't work with the linear gradient that the native Obsidian theme uses to truncate title bar text. Open a long file name and reduce the width of the popover to see what I mean there.

I think we're going to need to rely on theme developers customizing these things themselves as it's just too difficult to try and solve this neatly across all themes. We've made it pretty easy for theme developers and the popularity of Hover Editor should get them to adopt this pretty quickly :)

Noted on the updateLeaves() situation. I'll take a look at that.

**Comment by pjeby** [comment]
>  Open a long file name and reduce the width of the popover to see what I mean there.

I did that, but I'm not seeing a problem on any of over a dozen themes -- dark or light -- except "80's Neon".  Maybe I'm not understanding what it's supposed to look like, but it seems to me to still have a fade gradient?

But it's plenty for my requirements at this point because I'm only tweaking a few vars and the font weight.  I was momentarily confused when the is-active part didn't seem to be working with the latest commits, but it looks like that's because you added more background vars and I hadn't updated both inactive variants yet.

**Comment by nothingislost** [comment]
Yeah, I complicated it considerably by adding is-pinned into the mix so now there's a number of permutations.

Here's what I mean by the gradient problem which I caused by doing:
`--he-title-bar-inactive-bg: var(--background-modifier-cover);`
image

**Comment by pjeby** [comment]
Oh, I see.  The problem is when you *expand* the bar, not reduce it.  So I was testing it in a way that didn't show that issue at all.  Huh.  Ah well, maybe someday when all the browsers support CSS Color 5 "from" color calculations...  ;-)

**Comment by nothingislost** [comment]
You have no idea how much I wish I had color calculations :) It would've saved so much time!

**Pull request merged**
