### PR TITLE
Support for most split-related functionality

### PR DESCRIPTION
**Pull request by pjeby**
Changes include:

- Close the leaf menu on explicit hide if it's still open
- Don't break views (like backlinks) that may access leaf's getRoot() while closing
- Include popover leaves in normal iterateAll/iterateRoot
- Don't hide all the linked-pane functions (other than "link to pane") as they work now
- Ctrl/cmd click in a popover creates a split in it

I still haven't figured out how to get manual pane linking to work, so that's still disabled.

### CODE REVIEW

**Comment by pjeby** [comment]
Okay, figured out how to get linking working.  Dragging also works, in that you can drag a main leaf into an existing popup, but you can't drag it back out since there are no drag handles.

So the only thing needed to get that working is to remove the specialization of hoverleaves.  I think that this can be done by using plain leaves (with some compatibility patches at the prototype level) and moving the plugin-specific functionality (resolveLink, openLink, buildState, etc.) to a HoverOpener or some such class, that would add the extra functionality for opening links, tracking the state, and so on, as that functionality is only needed by code that sets up popovers.

**Comment by pjeby** [comment]
After some further work I've gotten it working with drag in/out and no need to switch leaf types around.  I need to get some sleep, though, before I review and push it.  (Feel free to merge the current state of this PR as-is if you like it so far; I can always put the currently-unreviewed stuff in a second PR.)

**Comment by pjeby** [comment]
Ok, I've pushed the further work.  If you want to try dragging panes, you can turn off the display: none.  I think some UI affordances are still required to distinguish dragging the popover versus the pane, and there may be some other pain (pane?) points with rearranging things besides that, but that's for later PRs and discussions.  :-)

**Comment by nothingislost** [comment]
This works great, nice job! I've been swamped with actual job lately so I was only able to test this briefly. For now I pushed 0.4.2 with this PR while leaving the drag icon hidden. I want to play around a bit with the UI/UX around how that drag icon coexists with the pin icon and the current popover drag capability before we enable it fully.

**Pull request merged**
