### PR TITLE
Fix #22 - commands not focusing/activating

### LINKED ISSUE #22: Keyboard commands (other than opening current file) don't activate or focus the new popover
This happens regardless of the "auto focus" setting, 

(Also, opening a popover for the current link does not create a new file when it doesn't exist.)

### PR DESCRIPTION
**Pull request by pjeby**
Ensure popovers created by commands are always active and focused, even if they are empty.  (Also creates missing files when following the link at the cursor, just like the built-in follow-link command.)

### CODE REVIEW

**Comment by nothingislost** [comment]
This is actually already in 0.3.5 but I'll take a look and see how our approaches differ. Thanks for the contribution!

**Comment by pjeby** [comment]
It looks like this is also fixing #8  (the part where you can't open an existing file in the new popover).

**Comment by pjeby** [comment]
(0.3.5 didn't fix any of my issues, btw, this PR is on top of 0.3.5)

**Comment by nothingislost** [comment]
Oops, yeah, a lot of this logic is in 0.3.6 which is not released yet. We were working on the same thing at the same time :)

**Comment by nothingislost** [comment]
I just pushed the outstanding commits. I'll do the work to resolve the conflicts and take on anything you did better :)

**Comment by pjeby** [comment]
Clearly I should have procrastinated more.  :wink:    I've also already merged your conflicts, and tested the result to make sure it still works.

**Comment by nothingislost** [comment]
Nice, thank you again! The fix to #8 works great.

**Comment by pjeby** [comment]
As it happens, it's also a fix for #4 (the "create without needing to click" part, that is).  :wink:

**Pull request merged**
